<a href="https://colab.research.google.com/github/codewithdark-git/TensorFlow/blob/main/Tensor_in_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install tensorflow

In [3]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [6]:
# Initialize of tensors
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [7]:
x= tf.constant(4, shape=(1,1))
print(x)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [8]:
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [9]:
x2 = tf.constant([[1,2,3],[4,5,6]])
print(x2)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [10]:
ones = tf.ones((2,3))
print(ones)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [11]:
zero = tf.zeros((2,3))
print(zero)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [12]:
zero = tf.zeros((2,3), dtype=tf.int32)
print(zero)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [15]:
eyes = tf.eye(3,3)
print(eyes)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [19]:
random = tf.random.normal((3,3))
print(random)

tf.Tensor(
[[ 0.2296558   0.2815364   0.03042188]
 [-0.28178683  1.0584239  -1.0270708 ]
 [ 2.0954523   0.46484837  0.25404206]], shape=(3, 3), dtype=float32)


In [20]:
random_normal = tf.random.normal((3,3), mean=0, stddev=1)
print(random_normal)

tf.Tensor(
[[-0.7739985  -0.32005873 -1.0757843 ]
 [-0.09976194 -0.8561527   0.17648393]
 [-0.08770095 -0.18359204  0.6220945 ]], shape=(3, 3), dtype=float32)


In [21]:
ran_uni = tf.random.uniform((3,3))
print(ran_uni)

tf.Tensor(
[[0.73855865 0.44523787 0.32229948]
 [0.02518511 0.4333099  0.28262377]
 [0.7588123  0.19590461 0.9822072 ]], shape=(3, 3), dtype=float32)


In [23]:
ran_uni = tf.random.uniform((3,3), minval=-2, maxval=2)
print(ran_uni)

tf.Tensor(
[[-1.5806389   0.67426777  1.0335803 ]
 [-0.42102623 -1.0356078   0.62705994]
 [ 0.7365947  -1.9900422   0.4278493 ]], shape=(3, 3), dtype=float32)


In [25]:
range = tf.range(10)
print(range)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [24]:
range = tf.range(start=1, limit=10, delta=2)
print(range)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [26]:
range = tf.cast(range, dtype=tf.float32)
print(range)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)


In [27]:
# Mathematical operations

x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = tf.add(x,y)
print(z)


tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [28]:
z = tf.subtract(x,y)
print(z)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [29]:
z = tf.multiply(x,y)
print(z)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [30]:
z = tf.divide(x,y)
print(z)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [34]:
z = tf.tensordot(x,y, axes=1)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [36]:
z = tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [40]:
X = tf.random.normal((2,3))
Y = tf.random.normal((3,4))

z = tf.matmul(X,Y)
print(z)

tf.Tensor(
[[ 4.30199     0.07413435 -1.4585658   1.6932184 ]
 [ 0.30486214  1.0509872  -0.29182154  0.29881695]], shape=(2, 4), dtype=float32)


In [41]:
z = X @ Y
print(z)

tf.Tensor(
[[ 4.30199     0.07413435 -1.4585658   1.6932184 ]
 [ 0.30486214  1.0509872  -0.29182154  0.29881695]], shape=(2, 4), dtype=float32)


In [42]:
# indexing

x = tf.constant([0,1,1,2,3,1,2,3])
print(x[:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)


In [43]:
print(x[1:])

tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)


In [44]:
print(x[1:3])

tf.Tensor([1 1], shape=(2,), dtype=int32)


In [45]:
print(x[::2])

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [46]:
print(x[::-1])

tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [47]:
indices = tf.constant([0,3])
x_ind = tf.gather(x, indices)
print(x_ind)


tf.Tensor([0 2], shape=(2,), dtype=int32)


In [49]:
x = tf.constant([[1,2],
                [3,4],
                [5,6]])
print(x[0,:])
print(x[0:2, :])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [50]:
# reshaping

x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [51]:
x = tf.reshape(x, (3,3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [52]:
x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


In [55]:
import numpy as np

x = np.array([1, 2,4,3])

x = tf.convert_to_tensor(x, dtype=tf.float32)
print(x)
print(x.numpy())


tf.Tensor([1. 2. 4. 3.], shape=(4,), dtype=float32)
[1. 2. 4. 3.]
